### ISSUE TITLE
Linking to "static" pages

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#100]
It should be possible to direct user to a specific 'static' page using url. For instance, it is necessary to provide direct link to page where collections and data usage rules are explained. Currently this is possible only within the application.

**Comment by enmust** [comment]
Added 'static' pages to all slider pages:
[News](http://geocollections.info/news)
[Using collections](http://geocollections.info/using_collections)
[About collections](http://geocollections.info/geocollections)
[Database](http://geocollections.info/database)
[GIT](http://geocollections.info/about_git)
[TUG](http://geocollections.info/about_tug)
[ELM](http://geocollections.info/about_elm)
[HELP](http://geocollections.info/help)
