### ISSUE TITLE
Search tips as popup

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#101]
If global search box is activated, a search tips popup should be shown. If the text is too much for a  popup that is always shown, maybe add a link "search tips" under the search box. 

Tips texts:

- Sisesta märksõna(d) kiireks otsinguks kõigist tabelitest. Suur- ja väiketähti ei eristata, 'wildcard' märgina kasutada "*".
- Mitme märksõna korral otsitakse vasteid, kus esineb vähemalt üks otsitavatest. Et märksõna kindlasti tulemustes sisalduks, lisa selle ette "+". Kui soovid mõne termini välistada, siis kasuta märksõna ees "-". Näiteks: [+scolecodonts +valga -conjungaspis](http://geocollections.info/search/+scolecodonts%20+valga%20-conjungaspis).
- Mitmesõnalise väljendi otsimiseks ümbritse see jutumärkidega. Sama tee ka siis kui otsitav sisaldab erimärke, nagu - ja +, nt ["OM6-3"](http://geocollections.info/search/"om6-3").

In English:

- Enter term(s) for quickly searching through all tables. For wildcard use "*".
- In case of multiple terms the results will include any of the terms. To require a specific keyword to be present, precede it with +. To exclude a term, precede it with -. For instance: [+scolecodonts +valga -conjungaspis](http://geocollections.info/search/+scolecodonts%20+valga%20-conjungaspis). 
- To search exact expression, use double quotation marks. Use them also if the term includes special characters like + or -, for instance ["OM6-3"](http://geocollections.info/search/"om6-3").

**Comment by enmust** [comment]
Added help button to main page and on fast search page which redirect user to help slider. Also help button can be found under the useful info dropdown
