### ISSUE TITLE
Reference detail view, new genera described table

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#109]
@ollehints 
This [Reference](http://geokogud.info/reference/12) has one table called **New genera described**.
Where does it come from?

**Comment by ollehints** [comment]
taxon, where rank__id=14 (&reference_id=…)
but it is better to make the whole thing "New taxa described" / "Kirjeldatud taksonid", without criteria

**Comment by enmust** [comment]
Done + added links to fossil.info
