### ISSUE TITLE
Change site favicon 

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#11]
Change the default Spring favicon for something specific. Small hammers are attached as temporary solution.
![hammers_small](https://user-images.githubusercontent.com/14974887/32688394-72df1114-c6d8-11e7-9b7f-0e3dd52e5c75.png)

**Comment by enmust** [comment]
Changed favicon to small hammers
![image](https://user-images.githubusercontent.com/14908993/32774400-d41c8b4c-c934-11e7-8df7-6496a729e6a1.png)
