### ISSUE TITLE
hierarchy bug

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#111]
Estonian translation won't work:
https://api.geocollections.info/sample/?paginate_by=25&page=1&order_by=-id&format=json&multi_search=value:Adavere%20lade;fields:stratigraphy__stratigraphy,stratigraphy__stratigraphy_en,lithostratigraphy__stratigraphy,lithostratigraphy__stratigraphy_en,stratigraphy_free;lookuptype:hierarchy

But English one works:
https://api.geocollections.info/specimen/?paginate_by=25&page=1&order_by=-id&format=json&multi_search=value:Adavere%20Stage;fields:stratigraphy__stratigraphy,stratigraphy__stratigraphy_en,lithostratigraphy__stratigraphy,lithostratigraphy__stratigraphy_en,stratigraphy_free;lookuptype:hierarchy

**Comment by ollehints** [comment]
works if stratigraphy_free is omitted -- this cannot be searched hierarchically. but why english version works i did not catch
