### ISSUE TITLE
Implement file detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#122]
This new view, accessible at geocollections/file/1234 etc, should combine the current specimen_image, image and attachment views. The latter three should also stay available for backwards compatibility. Photo and specimen_image search/list views should remain working, but use internally the attachment table. All links from the list views should direct to .../file/... urls.

**Comment by enmust** [comment]
What are those fields called which contain info about 'key words' and 'remarks' http://geokogud.info/file/7239 (photo archive files)

**Comment by ollehints** [comment]
tags and remsrks

Olle Hints, PhD
Tallinn University of Technology, Department of Geology
olle.hints@ttu.ee, +372 5130157

**Comment by enmust** [comment]
https://api.geocollections.info/attachment/7239

**API returns**: tags is 'oliver lehnert' and remarks is empty. 
**In application**: This is tags 'Öland-Gotland excursion after Erlangen Meeting, 2004'
 and this is remarks 'vaid osa iseloomulikumaid pilte lisatud andmebaasi' but I don't see these values. 

These values come from other fields but I don't know which ones

**Comment by enmust** [comment]
Locality images now using attachment table

**Comment by enmust** [comment]
Specimen images now using attachment table

**Comment by enmust** [comment]
Should be done, reopen if some issues
