### ISSUE TITLE
File page headings for photos and specimen photos

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#130]
If the file detailed view shows: 
- photo archive image (e.g., http://geocollections.info/file/121553), then the H2 should be "Photo / Foto: $image_number", for example "Photo: OH18-7-1"
- specimen image (http://geocollections.info/file/121551), then the H2 should be "Image of specimen / 
Säiliku foto: $acronym $specimen_id (ID: $specimen__id)", for example "Image of specimen: GIT 500-198 (ID: 141390)"
- file - OK already

This should be followed by "File ID / Fail ID: $attachment_id" on the next line.

**Comment by enmust** [comment]
Done
