### ISSUE TITLE
search by keywords

### ISSUE THREAD

**Issue by ursulatoom** [geocollections/geokogud2#134]
In references. Search does not work correctly by keywords. Try "trace fossils".

**Comment by enmust** [comment]
Changed referencekeywords__keyword -> tags.
Before it gave only 4 results but now it gives 1183 results. 
@ollehints Should it keep using tags field or referencekeywords__keyword field.

**Comment by ollehints** [comment]
it should include both fields - one contains keywords from the original publication, the other is for keywords and subject tags by the database user(s).

**Comment by enmust** [comment]
Should be okay now
