### ISSUE TITLE
File detail view should show links to related objects

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#136]
File detail view should show links to related objects, e.g., specimens, references etc. Currently, if user lands into file page, he/she has no way to get back to related database records, e.g., http://geocollections.info/file/123769 should link back to http://geocollections.info/specimen/291272.

**Comment by ollehints** [comment]
NB this applies to "other files" only.

**Comment by enmust** [comment]
Have to find other way to get attach_link... fields, can't use attachment table default fields because then for example specimen image search starts taking too much time #139

**Comment by ollehints** [comment]
why not make another query directly to attachment_link based on attachment_id value?

**Comment by enmust** [comment]
Yes it would be easy but this app's detail view logic in java side is not
that straight forward when making multiple requests.
