### ISSUE TITLE
Specimen search by fossil name hierarchy

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#137]
Specimen search by fossil name uses hierarchical search by default. It seems to work on higher taxa and some genera (http://geocollections.info/specimen?specimen_number_1=1&specimen_number=&collection_id_1=1&collection_id=&classification_1=11&classification=&taxon_1=11&taxon=Leptaena&name_geology_1=1&name_geology=&country_1=1&country=&locality_1=1&locality=&stratigraphy_1=11&stratigraphy=&id_1=5&id=&depth_since_1=12&depth_since=&depth_to_1=13&depth_to=&agent_1=1&agent=&reference_1=1&reference=&original_type_1=1&original_type=&part_1=1&part=&date_taken_since_1=12&date_taken_since=&date_taken_to_1=13&date_taken_to=&dbs%5B%5D=1&dbs%5B%5D=2&dbs%5B%5D=3&dbs%5B%5D=4&dbs%5B%5D=5&dbs%5B%5D=6&currentTable=specimen&maxSize=5&paginateBy=25&sort=id&sortdir=DESC) but not for others (http://geocollections.info/specimen?specimen_number_1=1&specimen_number=&collection_id_1=1&collection_id=&classification_1=11&classification=&taxon_1=11&taxon=Kaljoprion&name_geology_1=1&name_geology=&country_1=1&country=&locality_1=1&locality=&stratigraphy_1=11&stratigraphy=&id_1=5&id=&depth_since_1=12&depth_since=&depth_to_1=13&depth_to=&agent_1=1&agent=&reference_1=1&reference=&original_type_1=1&original_type=&part_1=1&part=&date_taken_since_1=12&date_taken_since=&date_taken_to_1=13&date_taken_to=&dbs%5B%5D=1&dbs%5B%5D=2&dbs%5B%5D=3&dbs%5B%5D=4&dbs%5B%5D=5&dbs%5B%5D=6&currentTable=specimen&maxSize=5&paginateBy=25&sort=id&sortdir=DESC). Should be examined and corrected as this is among the most common search scenarios.

**Comment by enmust** [comment]
These are the API queries:
https://api.geocollections.info/specimen/?paginate_by=25&page=1&order_by=-id&format=json&specimenidentification__taxon__taxon__hierarchy=Leptaena
and
https://api.geocollections.info/specimen/?paginate_by=25&page=1&order_by=-id&format=json&specimenidentification__taxon__taxon__hierarchy=Kaljoprion

This seems to be more like API problem

**Comment by ollehints** [comment]
API behaviout to be examined, perhaps something related to models and NULL values.

**Comment by urtson** [comment]
Corrected the code in views.py, should now work. Please test.

**Comment by enmust** [comment]
Close if okay
