### ISSUE TITLE
Detail view translations

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#142]
If a record is not present in any detail view the message should be:
"Content not present" / "Lehe sisu ei ole kättesaadav" (currently Detail view not found!)
"The content you are looking is not present or not accessible. Go to the <a>main page</a> or start a <a>new search</a>." / "Lehekülje sisu ei ole kättesaadav. Minge <a>avalehele</a> või alustage <a>uut otsingut</a>".

**Comment by enmust** [comment]
Done

**Comment by ollehints** [comment]
could we make "start a new search" a link to detail search page of particular table, for instance http://geocollections.info/specimen/3061427 would have link to http://geocollections.info/specimen
