### ISSUE TITLE
Less new windows should be opened

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#143]
Usage of the database will often open many new windows. Perhaps it would be better if links from detail views to other detail views should open in the same window. Could test this with specimen and locality detail views.

**Comment by enmust** [comment]
So do you mean that if user is on locality or specimen detail view then all other detail view links should be opened in the same window

**Comment by ollehints** [comment]
yes. it seems this would be a more useful default setting.

On 10 Oct 2018, at 19:55, enmust <notifications@github.com<mailto:notifications@github.com>> wrote:


So do you mean that if user is on locality or specimen detail view then all other detail view links should be opened in the same window

**Comment by enmust** [comment]
Fixed it
