### ISSUE TITLE
Linking from image gallery

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#144]
In the image gallery opened from the specimen detail view (http://geocollections.info/specimen/303736#gallery) clicking on 'Picture detail view' should open the file view in the same (usually not fullscreen) window. Currently it opens a new tab in the opener window, which is inconvenient. Also, 'Picture detail view' should be more prominent, perhaps a colorful button instead of text, something like in https://fossiilid.geokogud.info/62?mode=in_baltoscandia&lang=en#gallery-3

**Comment by enmust** [comment]
Made the button same color like other anchor tags also made it a little bit larger. 
The example page you sent was currently down so I will change the button design if needed.
