### ISSUE TITLE
non-image file download button

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#145]
Non-image file (like pdf) detail view should display a more obvious element for downloading the file. Currently it is difficult for user to understand that file can be downloaded by clicking on the cryptic filename.
Perhaps make the (non image) file detail view (http://geocollections.info/file/124113) look like an image detail view, so that instead of medium-size image there will be non-obtrusive area (light gray fill, dark gray border?) of the same size as image and with text 'Download file' / 'Lae alla' in the middle. The title would then be "File" instead of image. FB link could stay in place.

**Comment by enmust** [comment]
Updated file view also opened new issue about FB share button. Currently the design remained in one column. 

If some further design changes or functionality needs improving then let me know.
