### ISSUE TITLE
Global search result should be data or message and extended search view.

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#15]
Global search results should only show the tabs which contain some data. E.g., search for 'om17-529' should only display samples tab. Search for 'om17-529a' should show no tabs but message: "Your quick search returned no results. Please use extended search and select, which kind of information you are searching." followed by the regular extended search view.

**Comment by enmust** [comment]
Now only showing tabs which contain data, and if search returns no results then extra information is shown.

**Comment by enmust** [comment]
What do you mean "followed by the regular extended search view". Do you mean the view which is opened when user clicks on **extended search** button?
