### ISSUE TITLE
Links in reference search view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#159]
The reference search view should have text/links or icons for three fields: doi, url and local pdf. 
doi is already there, url should come from the url field if url ends with '.pdf' (could be a pdf icon), local pdf link should be shown if particular attachment is not private (pdf icon but different color). If the local pdf issue cannot be resolved nicely because of API limitations to restrict access to private related records, we should go for doi and url fields (and url field can be populated automatically for public linked pdfs). Or can we potentially fix api? 
The same issue goes for quick search, but there it is easy limit the result to public information while creating the index.

**Comment by urtson** [comment]
API fixed

**Comment by ollehints** [comment]
API now returns local pdf filename if it is public: https://api.geocollections.info/reference/8511.
