### ISSUE TITLE
Extended search should first show specimens

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#16]
Extended search should by default show specimens as these are the most important objects in the database (and most commonly searched for). However, displaying specimen data is currently slow -- that is why samples are shown first. Options should be explored on how to load this tab in less than 1 s, showing the most recent rows in the database very quickly (other data may load later in the background).

**Comment by enmust** [comment]
Fixed the issue and got specimen data to load quite fast, but the downside is I had to remove images.
