### ISSUE TITLE
Specimen search criteria not working properly

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#20]
The definitions for the following autocomplete fields should be updated:
* Name of fossil (does not work) -- API call /taxon/?taxon__istartswith=$q&fields=taxon
* Mineral/rock (does not work) -- /rock/?multi_search=value:$q;fields:name,name_en;lookuptype:istartswith&fields=name,name_en&format=json
* Locality -- /locality/?multi_search=value:$q;fields:locality,locality_en;lookuptype:istartswith&fields=locality,locality_en&format=json
* Collection number -- collection/?number__icontains=160&fields=number&format=json, search should be done using string on field collection.number

A general question is how the autocomplete filters should work. One option would be that if user selects a value from the autocomplete list, the search will look for exact match using ID rather than string (and hence making it working quickly). But user can also input custom string and an operator 'contains', then the search is done using string and joined tables.

**Comment by enmust** [comment]
Closing this because newer autocomplete issue was made for specimen search
