### ISSUE TITLE
svg images not shown

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#201]
svg images are not embedded/shown correctly within detail view: https://geocollections.info/file/146224
They work on separate pages https://files.geocollections.info/7f/58/7f58b68d-e968-41f5-9b2f-9e645dbe8bf2.svg
And edit2: https://edit2.geocollections.info/attachment/146224 
But maybe this file is just too large?

**Comment by enmust** [comment]
Was trying to get medium svg that's why it wasn't loading
