### ISSUE TITLE
Search filters styling

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#24]
The search fields should show user-entered text more prominently, perhaps using different color and bold font. Currently it is difficult to grasp which criteria are specified. The text in field should never be small than field labels -- currently it is in case of autocomplete fields.
![capture2](https://user-images.githubusercontent.com/14974887/32690390-9f062aa4-c6fe-11e7-916f-c9f70152b901.PNG)

**Comment by enmust** [comment]
Made every extended search field like this: 
![image](https://user-images.githubusercontent.com/14908993/33163631-1ce5384c-d038-11e7-9cd6-1052d7b3b87c.png)
