### ISSUE TITLE
Search criteria should be visible after reload and using url

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#28]
If user refreshes a search page with some criteria and results, the results remain in place, but the criteria fields appear empty. This is bad when someone links to results page by url -- then selection criteria remain hidden and subselections will not work.

**Comment by enmust** [comment]
Last used search criteria is now visible after reload and after closing browser.(local storage) 
Also if opening a results link then search criteria is also visible.(session storage)
