### ISSUE TITLE
back-end becomes unresponsive

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#29]
After some playing around with random searches (on mobile device) the server turns unresponsive. Initially partial pages are displayed and then apache shows:

Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.
Reason: Error reading from remote server

CPU usage on server is low, both jenkins.war and geocollections.war have several tens of processes running. Free RAM is available on server, but maybe not for java.

**Comment by enmust** [comment]
Closing this issue because I already allocated more memory to Java. We have to wait and see if it changes anything because up to my knowledge the server hasn't crashed anymore.
