### ISSUE TITLE
Wrong linked reference ID in locality details form

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#3]
For instance http://arendus.geokogud.info/locality/876 shows links to many references. If you click the first reference (Männil, Ralf, 1966a) a reference details form opens but shows wrong data (Klaamann, 1984a).

**Comment by enmust** [comment]
Removed the link and made it like stratigraphy references.
### **Looks like that now:** 
![image](https://user-images.githubusercontent.com/14908993/32608013-80096338-c563-11e7-846c-021ac3f773ba.png)


### **Stratigraphy one looks like that:** 
![image](https://user-images.githubusercontent.com/14908993/32608075-b6a8fc6e-c563-11e7-92cf-9e5493306518.png)
