### ISSUE TITLE
Extended search sometimes returns messed up rows

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#30]
In almost all cases extended search for speciemens returns messed results: http://arendus2.geokogud.info/specimen?specimen_number_1=1&specimen_number=&collection_id_1=5&collection_id=&classification_1=1&classification=&taxon_1=1&taxon=&name_geology_1=1&name_geology=&country_1=1&country=&locality_1=1&locality=&stratigraphy_1=1&stratigraphy=&id_1=5&id=&fossil_1=1&fossil=&agent_1=1&agent=&reference_1=1&reference=&original_type_1=1&original_type=holotüüp&part_1=1&part=&tags_1=1&tags=&dbs%5B%5D=1&dbs%5B%5D=2&dbs%5B%5D=3&dbs%5B%5D=4&dbs%5B%5D=5&dbs%5B%5D=6&currentTable=specimen&maxSize=5&sort=id&sortdir=DESC

Name, locality, stratigraphy, and collector etc values get mixed within the resultset. Check by single record in detail view. A similar problem occurred earlier with different searches.

**Comment by enmust** [comment]
**Note to self:** Detail view gets correct information
Both specimen search and pictures get wrong information.
