### ISSUE TITLE
DOI detail view

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#39]
In geokogud.info there are some fields which I don't know where they come from. 
Everything exists but is little bit different from geokogud.info. 

**Generel info:**
- ~~Copyright agent (currently in shorter form)~~

**Download data:** (EDIT: found some of these from attachment table but I don't know if this is the right place to get them)

- ~~Type - currently just written "data file"~~

- ~~Description - currently using title~~

- Format - (shorter form)

Also DOI detail view needs some **Estonian** translations.

**Comment by ollehints** [comment]
copyright_agent_id is in the doi table (agent name should be available via copyright_agent__agent).
type should come from attachment__type__value & value_en
description~title at the time, will change in future
short format should come from attachment__format__file_extension

Eesti k - kuna põhiväljade väärtusi DOI standardis ei tõlgita, siis Creator=Creator, aga tabeli päises võiks olla 'Relation' asemel 'Seos' jne
