### ISSUE TITLE
Footer contains unnecessary info

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#4]
Footer has large heading "Questions and comments about the database and website! / Küsimused andmebaasi ja veebilehe kohta!" together with e-mail and phone support. These data could be shown simply in smaller font in the bottom of the page (together with licence info etc), phone number not necessary.

**Comment by enmust** [comment]
Removed the large heading. Now only showing e-mail in the bottom of the page. 
![image](https://user-images.githubusercontent.com/14908993/32483429-bb132f6a-c3a4-11e7-964c-5e3cf14f3d73.png)
