### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#41]
HTML page titles should be more informative if possible. For instance, title of detail view http://arendus2.geokogud.info/sample/142869 could be 'Geocollections of Estonia: Sample 142869'. For sample search view http://arendus2.geokogud.info/sample, it could be 'Geocollections of Estonia: Samples' and so on. Maybe it can it change with language too.

**Comment by enmust** [comment]
Made HTML page titles more informative as requested. Also they change with language.
