### ISSUE TITLE
Specimen name in table view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#54]
Specimen name in table view should be combined from the following fields and criteria:
* specimenidentification__taxon__taxon - if exists should be shown and linked to fossiilid.info using specimenidentification__taxon__id
* specimenidentification__name - if exists show and add " | " as separator 
* specimenidentificationgeologies__rock__name - if exists should be shown and linked to kivid.info using specimenidentificationgeologies__rock__id 
* specimenidentificationgeologies__name - if exists show and add " | " as separator 

Fossil names should be shown in italics. 
English name is the same except in minerals and rocks the specimenidentificationgeologies__rock__name_en and specimenidentificationgeologies__name_en fields should be used.

**Comment by enmust** [comment]
Specimen name in table view should be combined from the following fields and criteria:

- ~~specimenidentification__taxon__taxon - if exists should be shown and linked to fossiilid.info using specimenidentification__taxon__id~~

- ~~specimenidentification__name - if exists show and add " | " as separator~~

- specimenidentificationgeologies__rock__name - if exists should be shown and linked to kivid.info using specimenidentificationgeologies__rock__id

- specimenidentificationgeologies__name - if exists show and add " | " as separator

Fossil names should be shown in italics.
English name is the same except in minerals and rocks the specimenidentificationgeologies__rock__name_en and specimenidentificationgeologies__name_en fields should be used.

**Comment by enmust** [comment]
Can you put here an example where specimen_identification_geologies is used in specimen table view.
