### ISSUE TITLE
Filtering not working on sample field in analysis table

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#60]
@urtson API gives server error (500) when trying to filter sample field.
https://api.arendus.geokogud.info/analysis/140815?fields=sample&sample__icontains=87 doesn't work
but https://api.arendus.geokogud.info/analysis/140815?fields=sample&sample__exact=87198 works.

**Comment by ollehints** [comment]
The sufficient api call in this case is https://api.arendus.geokogud.info/analysis/140815?fields=sample as each analysis is linked to a single sample anyway. sample__icontains=87 does not work because sample=sample_id which is number.

**Comment by enmust** [comment]
Okay, I used sample__id instead of sample and got the analysis search working by sample id under additional criteria.
