### ISSUE TITLE
In specimen image search, institution filter has no effect

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#70]
When searching for specimen images, the institution filter has no effect. Works OK if "Search images" is not checked.
http://arendus.geokogud.info/specimen?specimen_number_1=1&specimen_number=&collection_id_1=1&collection_id=&classification_1=1&classification=lubjakivi&taxon_1=1&taxon=&name_geology_1=1&name_geology=&country_1=1&country=&locality_1=1&locality=&stratigraphy_1=1&stratigraphy=&id_1=5&id=&depth_since_1=12&depth_since=&depth_to_1=13&depth_to=&agent_1=1&agent=&reference_1=1&reference=&original_type_1=1&original_type=&part_1=1&part=&date_taken_since_1=12&date_taken_since=&date_taken_to_1=13&date_taken_to=&dbs%5B%5D=1&currentTable=specimen&maxSize=5&search_images=1&page=2&sort=id&sortdir=DESC

**Comment by enmust** [comment]
Fixed
