### ISSUE TITLE
DOI detail page long url

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#76]
DOI detail view should be accessible using DOI ID as well as full DOI identifier:
* http://geokogud.info/doi/18
* http://geokogud.info/doi/10.15152/GEO.18
The second option is more important as this address is registered in international DOI database and used to make the universal link operational: http://doi.org/10.15152/GEO.18

**Comment by enmust** [comment]
http://arendus.geokogud.info/doi/18
http://arendus.geokogud.info/doi/10.15152/GEO.18

Both links now working
