### ISSUE TITLE
specimen image details

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#77]
* Specimen image detail view main table should start with specimen number (specimen.specimen_id), which links to specimen detail page via specimen.id value. Photo ID is shown in heading anyway, not necessary to repeat in table.
* Device digitised should not duplicate device (http://arendus.geokogud.info/specimen_image/106488), would be empty in most cases
* Image type - maybe not necessary, mostly digital image anyway.

**Comment by enmust** [comment]
Updated specimen image detail view
