### ISSUE TITLE
images in locality detail view

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#79]
Images table in locality detail view (e.g., http://arendus.geokogud.info/locality/12270) should be changed to simple list of images, like in specimen details view. Popup should show author and date_taken/date_taken_free (NB currently the date shows data entry date). Images should be sorted by stars DESC and date_taken DESC.

**Comment by enmust** [comment]
Updated images table in locality detail view and currently sorting by date_taken.
what do you mean sorted by 'stars'?

**Comment by ollehints** [comment]
Added field stars to API. The numbers 1-5 denote relative quality of image, default is 0=not set.

**Comment by enmust** [comment]
Done
