### ISSUE TITLE
hierarchy multi search

### ISSUE THREAD

**Issue by enmust** [geocollections/geokogud2#91]
@urtson Is it possible to get multi search working using  hierarchy look up type. 
https://api.arendus.geokogud.info/sample/?paginate_by=25&page=1&order_by=-id&format=json&multi_search=value:Viru%20ladestik;fields:stratigraphy__stratigraphy,stratigraphy__stratigraphy_en,lithostratigraphy__stratigraphy,lithostratigraphy__stratigraphy_en,stratigraphy_free;lookuptype:hierarchy

**Comment by urtson** [comment]
Should now work
