### ISSUE TITLE
DOI numbers incorrect in solr results table

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#94]
DOI numbers and links in solr search are incorrectly show: 
http://arendus.geokogud.info/global/reference/1/100/hints%20puente%202017
Sometimes the data are entered wrongly, but the correct way is to have only the DOI number in the database which starts always with "10.". So the link aadress (https://doi.org/) should be added in code. 
As DOI numbers are sometimes quite long, maybe better to show some kind of link icon instead.
Same may then be applied to detailed search results table, where sometimes the links do not work also (due to inconsistent data entry): http://arendus.geokogud.info/reference?reference___id_1=5&reference___id=&author_1=1&author=&title_1=1&title=&journal_1=1&journal=&book_1=1&book=&abstracts_1=1&abstracts=&keywords_1=1&keywords=&currentTable=reference&maxSize=5&paginateBy=25&sort=id&sortdir=DESC&year_1=gte%20lte&year=2007%202017

**Comment by enmust** [comment]
Done
