### ISSUE TITLE
Quick search with no results

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#97]
Quick search with no results displays unnecessary information about page number etc:
http://arendus.geokogud.info/global/specimen/1/100/Tetrahedriit
Should only show "Your quick search returned no results. <br />Please try another more generic keyword or use extended search and select, which kind of information you are looking for." 
"Teie kiirotsing ei andnud tulemusi. <br />Palun proovige teisi märksõnu või kasutage detailotsingut".

**Comment by enmust** [comment]
Done
