### ISSUE TITLE
Show mp3 videos attached to specimens etc

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#98]
Attachment may be a video. Then it should be displaid as a link or, if possible, a preview in cases like: http://arendus.geokogud.info/specimen/291272 
Currently there seems to be no way to get to other files but images and pdfs. Sometimes different files need to be made available. Then a simple file icon should be displayed.   
Example from old system: http://geokogud.info/attachment/1801, and http://geokogud.info/files/c1/c12a85450aa4d448ba417882ef50e1d0.mp4

**Comment by enmust** [comment]
Added link for video + added video to detail view under attachments
