### ISSUE TITLE
Global search urls

### ISSUE THREAD

**Issue by ollehints** [geocollections/geokogud2#99]
The search page should be named "search" instead of "global".
The search string should come before tab and paging info.
Tab name, paging size and page number should be optional - if not present, the first filled tab, default paging size and first page should be shown.
The new url: http://geocollections.info/search/om16 or http://geocollections.info/search/om16/sample/1/100
instead of http://geocollections.info/global/sample/1/100/om16
This would allow easy search box from other systems, e.g., http://natarc.ut.ee/geokogud.php

**Comment by enmust** [comment]
Done, both ../search/om16 and ../search/om16/sample/1/100 are working
